name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1' # Specify the PHP version you need
          extensions: mbstring, xml, bcmath, curl, mysqli, pdo_mysql

      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Run Tests
        run: ./vendor/bin/phpunit

      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: build/reports/tests/**
